# Generated by Django 2.2.6 on 2019-10-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='date_last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='date_last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
