# Generated by Django 2.2.6 on 2020-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingService', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='delay_ms',
            field=models.IntegerField(default=999999),
        ),
    ]
